=== damianng1112/SOA_Microservices/bin/Wk2/phonesComplexTypes.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.phones.com"
    xmlns="http://www.phones.com"
    elementFormDefault="qualified">
    <xsd:element name="phones">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="phone" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element ref="type" />
                            <xsd:element ref="freeCallCredit" />
                            <xsd:element ref="currency" />
                            <xsd:element ref="number" />
                            <xsd:element ref="provider" />
                            <xsd:element ref="sold" />
                            <xsd:element ref="maker" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="type">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Pre-pay"></xsd:enumeration>
                <xsd:enumeration value="Bill-pay"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="freeCallCredit">
        <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
                <xsd:minExclusive value="10"></xsd:minExclusive>
                <xsd:maxExclusive value="30"></xsd:maxExclusive>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="currency">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="USD"></xsd:enumeration>
                <xsd:enumeration value="Euro"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="number">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="08\d{1}-\d{6}"></xsd:pattern>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="provider">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Three"></xsd:enumeration>
                <xsd:enumeration value="GoMo"></xsd:enumeration>
                <xsd:enumeration value="Vodafone"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="sold">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="profit" type="xsd:string" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="maker">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="name"/>
                <xsd:element ref="location"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="name" type="xsd:string" />
    <xsd:element name="location">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Europe"></xsd:enumeration>
                <xsd:enumeration value="North America"></xsd:enumeration>
                <xsd:enumeration value="South America"></xsd:enumeration>
                <xsd:enumeration value="Asia"></xsd:enumeration>
                <xsd:enumeration value="Australia"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== damianng1112/SOA_Microservices/Wk2/phones.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<phones	xmlns="http://www.phones.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.phones.com phonesComplexTypes.xsd">
    <phone>
        <type>Pre-pay</type>
        <freeCallCredit>20</freeCallCredit>
        <currency>Euro</currency>
        <number>085-123456</number>
        <provider>GoMo</provider>
        <sold>
            <profit>yes</profit>
        </sold>
        <maker>
            <name>Nokia</name>
            <location>Europe</location>
        </maker>
    </phone>
    <phone>
        <type>Bill-pay</type>
        <freeCallCredit>20</freeCallCredit>
        <currency>USD</currency>
        <number>086-656544</number>
        <provider>Three</provider>
        <sold>
            <profit>yes</profit>
        </sold>
        <maker>
            <name>Apple</name>
            <location>North America</location>
        </maker>
    </phone>
</phones>
