=== damianng1112/SOA_Microservices/Wk1/showroom.xsd
<?xml version="1.0"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.showroom.org"
xmlns="http://www.showroom.org"
elementFormDefault="qualified">
    <xsd:element name="showroom">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="car" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="car">
        <xsd:complexType> 
            <xsd:sequence> 
                <xsd:element ref="make" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="model" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="year" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="colour" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="transmission" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="engine" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="miles" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="price" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="make" type="xsd:string"></xsd:element>
    <xsd:element name="model" type="xsd:string"></xsd:element>
    <xsd:element name="year" type="xsd:string"></xsd:element>
    <xsd:element name="colour" type="xsd:string"></xsd:element>
    <xsd:element name="transmission">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="numGears" minOccurs="1" maxOccurs="1"></xsd:element>
                <xsd:element ref="type" minOccurs="1" maxOccurs="1"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
    <xsd:element name="engine">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="size" minOccurs="1" maxOccurs="1"></xsd:element>
                <xsd:element ref="fuel" minOccurs="1" maxOccurs="1"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="miles" type="xsd:string"></xsd:element>
    <xsd:element name="price" type="xsd:string"></xsd:element>
    <xsd:element name="numGears" type="xsd:string"></xsd:element>    
    <xsd:element name="type" type="xsd:string"></xsd:element>    
    <xsd:element name="size" type="xsd:string"></xsd:element>    
    <xsd:element name="fuel" type="xsd:string"></xsd:element>    
</xsd:schema>

=== damianng1112/SOA_Microservices/Wk1/showroom.xml
<?xml version="1.0" encoding="UTF-8"?>
<showroom xmlns="http://www.showroom.org"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.showroom.org showroom.xsd">
	<car>
		<make>Ford</make>
		<model>Mondeo</model>
		<year>2007</year>
		<colour>Red</colour>
		<transmission>
			<numGears>5</numGears>
			<type>Manual</type>
		</transmission>
		<engine>
			<size>1.8</size>
			<fuel>Petrol</fuel>
		</engine>
		<miles>98000</miles>
		<price>3500</price>
	</car>
	<car>
		<make>BMW</make>
		<model>320D</model>
		<year>2005</year>
		<colour>Black</colour>
		<transmission>
			<numGears>6</numGears>
			<type>Automatic</type>
		</transmission>
		<engine>
			<size>2.0</size>
			<fuel>Diesel</fuel>
		</engine>
		<miles>130000</miles>
		<price>4000</price>
	</car>
</showroom>
