=== damianng1112/SOA_Microservices/Wk2/studentComplexTypes.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.student.com"
    xmlns="http://www.student.com"
    elementFormDefault="qualified">
    <xsd:simpleType name="nameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\p{Lu}\p{Ll}+ \p{Lu}\p{Ll}+" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="genderType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Male" />
            <xsd:enumeration value="Female" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="phoneNumberType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{3}-\d{7}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="semesterRange">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"></xsd:minInclusive>
            <xsd:maxInclusive value="2"></xsd:maxInclusive>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="classSizeRange">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="2"></xsd:minInclusive>
            <xsd:maxInclusive value="30"></xsd:maxInclusive>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="favSubType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="SOA" />
            <xsd:enumeration value="Data Science" />
            <xsd:enumeration value="Agile Build and Delivery" />
            <xsd:enumeration value="Software Design" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="student">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="personal" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="nameType" />
                            <xsd:element name="dob" type="xsd:date" />
                            <xsd:element name="time" type="xsd:time" />
                            <xsd:element name="gender" type="genderType" />
                            <xsd:element name="weight" type="xsd:double" />
                            <xsd:element name="phoneNo" type="phoneNumberType" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="college" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="course">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="semester" type="semesterRange" />
                                        <xsd:element name="classSize" type="classSizeRange" />
                                        <xsd:element name="favouriteSubject" type="favSubType" />
                                    </xsd:sequence>
                                    <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="TUS"></xsd:enumeration>
                                    <xsd:enumeration value="UCD"></xsd:enumeration>
                                    <xsd:enumeration value="NUIG"></xsd:enumeration>
                                    <xsd:enumeration value="TUD"></xsd:enumeration>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                        <xsd:attribute name="studentID">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="A0\d{5}"></xsd:pattern>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== damianng1112/SOA_Microservices/Wk2/student.xml
<?xml version="1.0"?>
<student xmlns="http://www.student.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.student.com studentComplexTypes.xsd">
    <personal>        
        <name>Joe Bloggs</name>
        <dob>2000-01-22</dob>
        <time>10:12:03</time>
        <gender>Male</gender>
        <weight>8.7</weight>
        <phoneNo>087-1234567</phoneNo>
    </personal>
    <college name="TUS" studentID="A012345">
        <course name="MSc in S/W Eng">
            <semester>1</semester>
            <classSize>7</classSize>
            <favouriteSubject>SOA</favouriteSubject>
        </course>
    </college>
</student>
