=== damianng1112/SOA_Microservices/bin/Wk1/laptop.dtd
<!ELEMENT laptop (manufacturer, model, memory, disk, screen, accessories+)>
<!ELEMENT manufacturer (name, country, continent)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ELEMENT disk (#PCDATA)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT accessories (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT continent (#PCDATA)>

=== damianng1112/SOA_Microservices/Wk1/laptop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE laptop SYSTEM "laptop.dtd">
<laptop>
    <manufacturer>
        <name>Dell</name>
        <country>Poland</country>
        <continent>Europe</continent>
    </manufacturer>

    <model>Inspiron</model>
    <memory>512M</memory>
    <disk>60G</disk>
    <screen>15inch</screen>
    <accessories>Bag</accessories>
    <accessories>Mouse</accessories>
</laptop>
