=== damianng1112/SOA_Microservices/bin/Wk1/phonestore.xsd
<?xml version="1.0"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.phonestore.org"
xmlns="http://www.phonestore.org"
elementFormDefault="qualified">
    <xsd:element name="phonestore">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="phone" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="phone">
        <xsd:complexType> 
            <xsd:sequence> 
                <xsd:element ref="make" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="model" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="specs" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="price" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="make" type="xsd:string"></xsd:element>
    <xsd:element name="model" type="xsd:string"></xsd:element>
    <xsd:element name="specs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="memory" minOccurs="1" maxOccurs="1"></xsd:element>
                <xsd:element ref="os" minOccurs="1" maxOccurs="1"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="price" type="xsd:string"></xsd:element>
    <xsd:element name="memory" type="xsd:string"></xsd:element>
    <xsd:element name="os" type="xsd:string"></xsd:element>    
</xsd:schema>

=== damianng1112/SOA_Microservices/bin/Wk1/phonestore.xml
<?xml version="1.0" encoding="UTF-8"?>
<phonestore xmlns="http://www.phonestore.org"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.phonestore.org phonestore.xsd">
	<phone>
		<make>Samsung</make>
		<model>S6</model>
		<specs>
			<memory>2GB</memory>
			<os>Android</os>
		</specs>
		<price>500</price>
	</phone>
	<phone>
		<make>Apple</make>
		<model>i6</model>
		<specs>
			<memory>2GB</memory>
			<os>Apple OS</os>
		</specs>
		<price>600</price>
	</phone>
</phonestore>
